future: true
drafts: true
unpublished: true

_options:
  heading_html:
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    underline: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    styles: /editor.css
  body-content_html:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true
    bulletedlist: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    styles: /editor.css
  content:
    blockquote: true
    horizontalrule: true
    format: p h1 h2 h3 h4 h5 h6
    bold: true
    italic: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    center: align-to-center
    left: align-to-left
    embed: true
    link: true
    undo: true
    redo: true
    underline: true
    strike: true
    image: true
    bulletedlist: true
    styles: /editor.css
  embed-code_html:
    embed: true


page_blocks: []
_array_structures:
  page_blocks:
    - label: Text
      icon: library_books
      value:
        _id: text
        block-class:
        heading:
        description_html:
        link_url:
        link-text:
    - label: Banner
      icon: ballot
      value:
        _id: banner
        background_image:
        heading:
        link-text:
        link_url:
    - label: Fixed Background
      icon: perm_media
      value:
        _id: fixed-bg
        block-class:
        background_image:
        heading:
    - label: Quote With Image (Right)
      icon: perm_media
      value:
        _id: quote-img-right
        block-class:
        background_color: 
        featured_image:
        background_image:
        heading_html:
    - label: Quote With Image (Left)
      icon: perm_media
      value:
        _id: quote-img-left
        block-class:
        featured_image:
        background_image:
        heading:
    - label: Recent Blog Posts
      icon: ballot
      value:
        _id: recent-posts
        heading:
        link_url:
        link-text:
    - label: Sign Up Box
      icon: vertical_split
      value:
        _id: sign-up
        background_image:
        heading_html:
        embed-code_html:
    - label: Two Columns
      icon: vertical_split
      value:
        _id: two-col
        block-class:
        background-color:
        first-featured_image:
        heading:
        description_html:
        link_url:
        link-text:
        second-featured_image:
        second-heading:
        second-description_html:
        second-link_url:
        second-link-text:
    - label: Three Columns
      icon: view_column
      value:
        _id: three-col
        block-class:
        background-color:
        first-featured_image:
        heading:
        description_html:
        link_url:
        link-text:
        second-featured_image:
        second-heading:
        second-description_html:
        second-link_url:
        second-link-text:
        third-featured_image:
        third-heading:
        third-description_html:
        third-link_url:
        third-link-text:
