page_blocks: []
_array_structures:
  page_blocks:
    - label: Banner
      icon: ballot
      value:
        _id: banner
        background_image:
        block-class:
        heading:
        sub-heading:
        link-text:
        link_url:
    - label: fixed-bg
      icon: perm_media
      value:
        _id: fixed-bg
        background_image:
    - label: quote-img-left
      icon: perm_media
      value:
        _id: quote-img-right
        background_image:
        heading:
    - label: recent-posts
      icon: ballot
      value:
        _id: recent-posts
        heading:
        link-text:
        link_url: 
